# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Ray Villalobos"
description: > # this means to ignore newlines until "email:"
   Father of 8, Lynda.com Staff Author & Speaker

email: ray@planetoftheweb.com
logo: "/assets/images/powship.png" #blog logo
cover: "/assets/images/hero.jpg" # blog cover

name: 'Ray Villalobos'
author: 'Ray Villalobos'
author_image: "/assets/images/author.jpg"
ldcjsonfeed: http://planetoftheweb.com/i/courses.php?author=832401&limit=0&filter.includes=Title,ShortDescription,DurationInSeconds,URLs,ID,WelcomeVideoId,Thumbnails.filename

paginate:	5

url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/planetoftheweb
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:  https://facebook.com/viewsource
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: linkedin
    url:  https://linkedin.com/in/planetoftheweb
    desc: Connect with me on LinkedIn

  - icon:	github
    url:	https://github.com/planetoftheweb
    desc:	Fork me on github

  - icon:	google-plus
    url:	https://plus.google.com/+RayVillalobos0
    desc:	Add me on google+

  - icon:	dribbble
    url:	https://dribbble.com/planetoftheweb
    desc:	Follow me on dribbble

  - icon:	flickr
    url:	https://www.flickr.com/photos/planetoftheweb/sets/72157602932636630/
    desc:	My flickr portfolio

  - icon:	youtube
    url:	https://www.youtube.com/user/planetoftheweb
    desc:	Subscribe to my youtube channel
