# Site settings
title: Planetoftheweb
email: ray@planetoftheweb.com
description: > # this means to ignore newlines until "baseurl:"
	This is the project site for @planetoftheweb a.k.a. Ray Villalobos, Staff Author for Lynda.com.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://planetoftheweb.github.io" # the base hostname & protocol for your site
twitter_username: planetoftheweb
github_username:  planetoftheweb

# Build settings
markdown: kramdown
