# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Planet of the Web"
description: > # this means to ignore newlines until "email:"
   Ray Villalobos, Father of 8, Lynda.com Staff Author & Speaker

email: ray@planetoftheweb.com
#blog logo
logo: "/assets/images/powship.png"
# blog cover
cover: "/assets/images/hero.jpg"

name: 'Ray Villalobos'
author: 'Ray Villalobos'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://planetoftheweb.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/planetoftheweb
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:  https://facebook.com/iviewsource
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: linkedin
    url:  https://linkedin.com/in/planetoftheweb
    desc: Connect with me on LinkedIn
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/planetoftheweb
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+RayVillalobos0
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
